name: Daily Weather Post
on:
  schedule:
    - cron: '0 7 * * *' # Codziennie o 7:00 rano UTC
  workflow_dispatch: # Pozwala odpalić bota ręcznie przyciskiem

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run bot
        env:
          IG_USERNAME: ${{ secrets.IG_USERNAME }}
          IG_PASSWORD: ${{ secrets.IG_PASSWORD }}
          WEATHER_API: ${{ secrets.WEATHER_API }}
        run: python main.py
