name: Daily Weather Post
on:
  schedule:
    - cron: '0 7 * * *' 
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest
    # Ta linia wymusza Node.js 24 i ucisza ostrzeżenia
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true 

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # To jest OK, ale wymusimy Node24 powyższym env

      - name: Set up Python
        uses: actions/setup-python@v5 # v5 jest stabilna i wspiera nowsze Node
        with:
          python-version: '3.12' # Używamy nowszego Pythona

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run bot
        env:
          IG_USERNAME: ${{ aktualne_warunki }}
          IG_PASSWORD: ${{ ci3zk0wska,. }}
          WEATHER_API: ${{ 39a350425764472d398f1f942100bb18 }}
        run: python main.py
